import { fonts, fontStyles, fontWeights } from '../fonts';

export default {
  'text-xl': {
    fontFamily: fonts.body,
    fontSize: '21px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.normal,
    lineHeight: '32px',
    textTransform: 'none' as any,
  },
  'text-xl-medium': {
    fontFamily: fonts.body,
    fontSize: '21px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.medium,
    lineHeight: '32px',
    textTransform: 'none' as any,
  },
  'text-xl-bold': {
    fontFamily: fonts.body,
    fontSize: '21px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.bold,
    lineHeight: '32px',
    textTransform: 'none' as any,
  },
  'text-l': {
    fontFamily: fonts.body,
    fontSize: '18px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.normal,
    lineHeight: '24px',
    textTransform: 'none' as any,
  },
  'text-l-medium': {
    fontFamily: fonts.body,
    fontSize: '18px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.medium,
    lineHeight: '24px',
    textTransform: 'none' as any,
  },
  'text-l-bold': {
    fontFamily: fonts.body,
    fontSize: '18px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.bold,
    lineHeight: '24px',
    textTransform: 'none' as any,
  },
  'text-m': {
    fontFamily: fonts.body,
    fontSize: '16px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.normal,
    lineHeight: '24px',
    textTransform: 'none' as any,
  },
  'text-m-medium': {
    fontFamily: fonts.body,
    fontSize: '16px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.medium,
    lineHeight: '24px',
    textTransform: 'none' as any,
  },
  'text-m-bold': {
    fontFamily: fonts.body,
    fontSize: '16px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.bold,
    lineHeight: '24px',
    textTransform: 'none' as any,
  },
  'text-s': {
    fontFamily: fonts.body,
    fontSize: '14px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.normal,
    lineHeight: '16px',
    textTransform: 'none' as any,
  },
  'text-s-medium': {
    fontFamily: fonts.body,
    fontSize: '14px',
    fontStyle: fontStyles.normal,
    fontWeight: fontWeights.medium,
    lineHeight: '16px',
    textTransform: 'none' as any,
  },
};
